name: Build

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        version: [18.04, 20.04]
        toolchain:
          - name: "GCC"
            install: "g++"
            cc: gcc
            cxx: g++
            ar: ar
            ranlib: ranlib
            ldflags: ""

          - name: "LLVM"
            install: "llvm clang lld"
            cc: clang
            cxx: clang++
            ar: llvm-ar
            ranlib: llvm-ranlib
            ldflags: "-fuse-ld=lld"

    runs-on: ubuntu-${{matrix.version}}
    name: Ubuntu ${{matrix.version}} ${{matrix.toolchain.name}} build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ${{matrix.toolchain.name}}
        run: sudo apt-get install -y $TOOLCHAIN

        env:
          TOOLCHAIN: ${{matrix.toolchain.install}}

      - name: Toolchain summary
        run: echo "Archiver=$(which $AR) ; Ranlib=$(which $RANLIB) ; CC=$CC ; CXX=$CXX ; LDflags=$LDFLAGS"

        env:
          CC: ${{matrix.toolchain.cc}}
          CXX: ${{matrix.toolchain.cxx}}
          AR: ${{matrix.toolchain.ar}}
          RANLIB: ${{matrix.toolchain.ranlib}}
          LDFLAGS: ${{matrix.toolchain.ldflags}}

      - name: Setup project deps
        working-directory: ${{github.workspace}}/dist
        run: sudo ./get-deps-debian.sh

        env:
          CC: ${{matrix.toolchain.cc}}
          CXX: ${{matrix.toolchain.cxx}}
          AR: ${{matrix.toolchain.ar}}
          RANLIB: ${{matrix.toolchain.ranlib}}
          LDFLAGS: ${{matrix.toolchain.ldflags}}

      - name: Generate project
        run: >
          mkdir build &&
          cd build &&
          cmake --log-level=DEBUG -DCMAKE_SYSTEM_PREFIX_PATH="../dist/install" -DCMAKE_BUILD_TYPE=Release -DCMAKE_AR=$(which $AR) -DCMAKE_RANLIB=$(which $RANLIB) ..

        env:
          CC: ${{matrix.toolchain.cc}}
          CXX: ${{matrix.toolchain.cxx}}
          AR: ${{matrix.toolchain.ar}}
          RANLIB: ${{matrix.toolchain.ranlib}}
          LDFLAGS: ${{matrix.toolchain.ldflags}}

      - name: Build project
        working-directory: ${{github.workspace}}/build
        run: cmake --build . -- -j2

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest

      - name: Install project
        working-directory: ${{github.workspace}}/build
        run: sudo cmake --install .

  build-mingw:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    strategy:
      fail-fast: false
      matrix:
        msys:
          - architecture: x86_64
            env: MINGW64

          - architecture: i686
            env: MINGW32

    name: Windows ${{matrix.msys.env}} build
    steps:
      - name: Setup msys2 for ${{matrix.msys.env}}
        uses: msys2/setup-msys2@v2

        with:
          msystem: ${{matrix.msys.env}}
          update: true
          install: >
            mingw-w64-${{matrix.msys.architecture}}-gcc
            mingw-w64-${{matrix.msys.architecture}}-cmake
            mingw-w64-${{matrix.msys.architecture}}-make

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup project deps
        working-directory: ${{github.workspace}}/dist
        run: ./get-deps-msys2.sh

      - name: Generate project
        run: >
          mkdir build &&
          cd build &&
          cmake --log-level=DEBUG -DCMAKE_SYSTEM_PREFIX_PATH="../dist/install" -DCMAKE_BUILD_TYPE=Release -G"MinGW Makefiles" ..

      - name: Build project
        working-directory: ${{github.workspace}}/build
        run: cmake --build . -- -j2

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest

      - name: Install project
        working-directory: ${{github.workspace}}/build
        run: cmake --install .