name: Windows Build

on:
  push:
  pull_request:

jobs:
  build-mingw:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    strategy:
      fail-fast: false
      matrix:
        msys:
          - architecture: x86_64
            env: MINGW64
            bits: 64
            suffix: x

    name: Windows ${{matrix.msys.env}} build
    steps:
      - name: Setup msys2 for ${{matrix.msys.env}}
        uses: msys2/setup-msys2@v2

        with:
          msystem: ${{matrix.msys.env}}
          update: true
          install: >
            mingw-w${{matrix.msys.bits}}-${{matrix.msys.architecture}}-gcc
            mingw-w${{matrix.msys.bits}}-${{matrix.msys.architecture}}-cmake
            mingw-w${{matrix.msys.bits}}-${{matrix.msys.architecture}}-make

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup pacman deps
        run: >
          pacman --sync
          mingw-w${{matrix.msys.bits}}-${{matrix.msys.architecture}}-boost
          mingw-w${{matrix.msys.bits}}-${{matrix.msys.architecture}}-spdlog
          mingw-w${{matrix.msys.bits}}-${{matrix.msys.architecture}}-nlohmann-json
          mingw-w${{matrix.msys.bits}}-${{matrix.msys.architecture}}-lua
          mingw-w${{matrix.msys.bits}}-${{matrix.msys.architecture}}-sol2

      - name: Generate project
        run: >
          mkdir build &&
          cd build &&
          cmake --log-level=DEBUG -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        working-directory: ${{github.workspace}}/build
        run: cmake --build . -- -j2

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest

      - name: Install project
        working-directory: ${{github.workspace}}/build
        run: cmake --install .
